WIP + simplified mso commands

diff --git a/examples/ms_office/cmd/my_unzip b/examples/ms_office/cmd/my_unzip
--- a/examples/ms_office/cmd/my_unzip
+++ b/examples/ms_office/cmd/my_unzip
@@ -2,25 +2,20 @@
 
 ################################################################################
 
-function exitApp() {
-  (( ${#} >= 2 )) && echo "${2}"
-  exit ${1}
-}
-
-################################################################################
-
-(( ${#} != 2 )) && exitApp 1 "Invalid number of parameters: ${#} (expected: 2)"
-
-################################################################################
-
 DIR="${1}"
 INP="${2}"
 
 ################################################################################
 
-mkdir -p "${DIR}" || exitApp 1 "Failed to create directory: \"${DIR}\""
-unzip -o -d "${DIR}" "${INP}" || exitApp 1 "Failed to unzip \"${INP}\" to directory: \"${DIR}\""
+if [[ "${DIR}" != "" ]] && [[ "${INP}" != "" ]]; then
+  mkdir -p "${DIR}" &&\
+  unzip -o -d "${DIR}" "${INP}" &&\
+  exit 0
+fi
 
-exitApp 0
+################################################################################
+
+echo "Failed to unzip \"${INP}\" to \"${DIR}\""
+exit 1
 
 ################################################################################
